# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Dylann/source/repos/takitsu21/ai-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Dylann/source/repos/takitsu21/ai-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Dylann/source/repos/takitsu21/ai-game/CMakeFiles /mnt/c/Users/Dylann/source/repos/takitsu21/ai-game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Dylann/source/repos/takitsu21/ai-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ai_game

# Build rule for target.
ai_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ai_game
.PHONY : ai_game

# fast build rule for target.
ai_game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/build
.PHONY : ai_game/fast

AIGame.o: AIGame.cpp.o

.PHONY : AIGame.o

# target to build an object file
AIGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/AIGame.cpp.o
.PHONY : AIGame.cpp.o

AIGame.i: AIGame.cpp.i

.PHONY : AIGame.i

# target to preprocess a source file
AIGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/AIGame.cpp.i
.PHONY : AIGame.cpp.i

AIGame.s: AIGame.cpp.s

.PHONY : AIGame.s

# target to generate assembly for a file
AIGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/AIGame.cpp.s
.PHONY : AIGame.cpp.s

src/Board.o: src/Board.cpp.o

.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i

.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s

.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/IA.o: src/IA.cpp.o

.PHONY : src/IA.o

# target to build an object file
src/IA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/src/IA.cpp.o
.PHONY : src/IA.cpp.o

src/IA.i: src/IA.cpp.i

.PHONY : src/IA.i

# target to preprocess a source file
src/IA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/src/IA.cpp.i
.PHONY : src/IA.cpp.i

src/IA.s: src/IA.cpp.s

.PHONY : src/IA.s

# target to generate assembly for a file
src/IA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ai_game.dir/build.make CMakeFiles/ai_game.dir/src/IA.cpp.s
.PHONY : src/IA.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ai_game"
	@echo "... AIGame.o"
	@echo "... AIGame.i"
	@echo "... AIGame.s"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/IA.o"
	@echo "... src/IA.i"
	@echo "... src/IA.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

